# Generated by Django 3.2.3 on 2021-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210426_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
